/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Unique id for a component
 */
export type Id = string;
/**
 * Optional variable name associated with a component
 */
export type VariableName = string;
/**
 * Vue component name
 */
export type Component = string;
/**
 * Options for the autocomplete box. Can be a list of strings or integers
 */
export type Items = (string | number)[];
/**
 * Selected option for the autocomplete box
 */
export type Value = string | number | null;
/**
 * Label for the autocomplete box
 */
export type Label = string | null;
/**
 * Determines if multiple selections are allowed
 */
export type Multiple = boolean | null;
/**
 * Determines if the autocomplete box has a clearable option
 */
export type Clearable = boolean | null;
/**
 * Determines if the autocomplete box is disabled
 */
export type Disabled = boolean | null;
/**
 * Determines if the autocomplete box is read-only
 */
export type Readonly = boolean | null;
/**
 * Color of the autocomplete component. Can be custom or standard Material color
 */
export type Color = string | null;
/**
 * Trigger event for when to run based on the selected value
 */
export type Triggerevent = string;

/**
 * Autocomplete is a select box that allows users to search the available options.
 * Optimal for when there are many options to choose from
 */
export interface Autocomplete {
  id: Id;
  variable_name?: VariableName;
  component?: Component;
  items?: Items;
  value?: Value;
  label?: Label;
  multiple?: Multiple;
  clearable?: Clearable;
  disabled?: Disabled;
  readonly?: Readonly;
  color?: Color;
  triggerEvent?: Triggerevent;
  [k: string]: unknown;
}
