/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Unique id for a component
 */
export type Id = string;
/**
 * Optional variable name associated with a component
 */
export type VariableName = string;
/**
 * Vue component name.
 */
export type Component = string;
/**
 * Whether the button has been clicked
 */
export type Value = boolean;
/**
 * Label displayed on the button.
 */
export type Text = string;
/**
 * Color of the button.
 */
export type Color = string;
/**
 * If true, the button is disabled.
 */
export type Disabled = boolean;
/**
 * If true, the button will have an outlined style.
 */
export type Outlined = boolean;
/**
 * Trigger event to send code to the backend
 */
export type Triggerevent = string;

/**
 * A class for Button components inheriting from ZTComponent.
 */
export interface Button {
  id: Id;
  variable_name?: VariableName;
  component?: Component;
  value?: Value;
  text?: Text;
  color?: Color;
  disabled?: Disabled;
  outlined?: Outlined;
  triggerEvent?: Triggerevent;
  [k: string]: unknown;
}
