/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Unique id for a component
 */
export type Id = string;
/**
 * Optional variable name associated with a component
 */
export type VariableName = string;
/**
 * Vue component name.
 */
export type Component = string;
/**
 * List of child components within the card.
 */
export type Cardchildren = string[];
/**
 * Background color of the card.
 */
export type Color = string;
/**
 * Elevation level of the card. Must be between 0 and 24.
 */
export type Elevation = number;
/**
 * Density of the component
 */
export type Density = "default" | "comfortable" | "compact";
/**
 * Width of the card.
 */
export type Width = number;
export type Location = "center";

/**
 * A class for Card components inheriting from ZTComponent.
 */
export interface Card {
  id: Id;
  variable_name?: VariableName;
  component?: Component;
  cardChildren?: Cardchildren;
  color?: Color;
  elevation?: Elevation;
  density?: Density;
  width?: Width;
  location?: Location;
  [k: string]: unknown;
}
