/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Comment = Comment1;
export type Id = string;
export type Comment2 = string;
export type Date = string;
export type Resolved = boolean;

export interface Comment1 {
  id: Id;
  comment: Comment2;
  date: Date;
  replies?: Replies;
  resolved?: Resolved;
  [k: string]: unknown;
}
export interface Replies {
  [k: string]: Comment1;
}
