/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Componentid = string;
export type Componentvalue = string | boolean | number;

export interface ComponentRequest {
  componentId: Componentid;
  componentValue: Componentvalue;
  [k: string]: unknown;
}
