/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Originid = string;
export type Componentid = string;
export type Componentvalue = string | boolean | number | unknown[] | null;

export interface ComponentRequest {
  originId: Originid;
  componentId: Componentid;
  componentValue: Componentvalue;
  [k: string]: unknown;
}
