/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Celltype = "code" | "markdown" | "text" | "sql";
export type PositionKey = string;

export interface CreateRequest {
  cellType: Celltype;
  position_key: PositionKey;
  [k: string]: unknown;
}
