/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Unique id for a component
 */
export type Id = string;
/**
 * Optional variable name associated with a component
 */
export type VariableName = string;
/**
 * Vue component name
 */
export type Component = string;
/**
 * Hide the days of the week letters in the calendar view
 */
export type HideWeekdays = boolean | null;
/**
 * Puts the Date Picker component into landscape mode.
 */
export type Landscape = boolean | null;
/**
 * Sets the icon for next month/year button in the Date Picker Component
 */
export type NextIcon = string;
/**
 * Sets the icon for prev month/year button in the Date Picker Component
 */
export type PrevIcon = string;
/**
 * Determines which picker is being displayed. Allowed values: 'month', 'months', 'year'
 */
export type ViewMode = "month" | "months" | "year";
/**
 * An array of weekdays to display
 */
export type Weekdays = number[] | null;
/**
 * Determines if the Date Picker component is disabled
 */
export type Disabled = boolean | null;
/**
 * Color of the Calendar. Can be custom or standard Material color
 */
export type Color = string | null;
/**
 * Width of the Date Picker component
 */
export type Width = number | null;
/**
 * Height of the Date Picker component
 */
export type Height = number | null;
/**
 * Trigger event for when to run based on the selected value
 */
export type Triggerevent = string;

/**
 * Date Picker component allows a user to select a date
 */
export interface DatePicker {
  id: Id;
  variable_name?: VariableName;
  component?: Component;
  hide_weekdays?: HideWeekdays;
  landscape?: Landscape;
  next_icon?: NextIcon;
  prev_icon?: PrevIcon;
  view_mode?: ViewMode;
  weekdays?: Weekdays;
  disabled?: Disabled;
  color?: Color;
  width?: Width;
  height?: Height;
  triggerEvent?: Triggerevent;
  [k: string]: unknown;
}
