/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Package = string;
export type Version = string;

export interface Dependency {
  package: Package;
  version?: Version;
  [k: string]: unknown;
}
