/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Cellid = string;
export type Parentcommentid = string;
export type Commentid = string;
export type Comment = string;

export interface EditReplyRequest {
  cellId: Cellid;
  parentCommentId: Parentcommentid;
  commentId: Commentid;
  comment: Comment;
  [k: string]: unknown;
}
