/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Unique id for a component
 */
export type Id = string;
/**
 * Optional variable name associated with a component
 */
export type VariableName = string;
/**
 * Vue component name for file input
 */
export type Component = string;
/**
 * Accepted file types (e.g., '.png, .jpg')
 */
export type Accept = string | null;
/**
 * Placeholder text for file input
 */
export type Placeholder = string | null;
/**
 * Label for the file input
 */
export type Label = string | null;
/**
 * If true, allows multiple files
 */
export type Multiple = boolean | null;
/**
 * If true, shows file size
 */
export type ShowSize = boolean | null;
/**
 * If true, the input is read-only
 */
export type Readonly = boolean | null;
/**
 * If true, the input is disabled
 */
export type Disabled = boolean | null;
/**
 * If true, allows clearing of the input
 */
export type Clearable = boolean | null;
/**
 * If true, shows a file count indicator
 */
export type Counter = boolean | null;
/**
 * Trigger event to send code to the backend
 */
export type Triggerevent = string;

/**
 * File input component allowing users to upload files.
 */
export interface FileInput {
  id: Id;
  variable_name?: VariableName;
  component?: Component;
  value?: unknown;
  accept?: Accept;
  placeholder?: Placeholder;
  label?: Label;
  multiple?: Multiple;
  show_size?: ShowSize;
  readonly?: Readonly;
  disabled?: Disabled;
  clearable?: Clearable;
  counter?: Counter;
  triggerEvent?: Triggerevent;
  [k: string]: unknown;
}
