/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Cellid = string;
export type Hidecode = boolean;

export interface HideCodeRequest {
  cellId: Cellid;
  hideCode: Hidecode;
  [k: string]: unknown;
}
