/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Unique id for a component
 */
export type Id = string;
/**
 * Optional variable name associated with a component
 */
export type VariableName = string;
/**
 * Vue component name
 */
export type Component = string;
/**
 * HTML content of the component
 */
export type VHtml = string;

/**
 * This is a component is used to render arbitrary HTML
 */
export interface HTML {
  id: Id;
  variable_name?: VariableName;
  component?: Component;
  v_html?: VHtml;
  [k: string]: unknown;
}
