/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Unique id for a component
 */
export type Id = string;
/**
 * Optional variable name associated with a component
 */
export type VariableName = string;
/**
 * Vue component name
 */
export type Component = string;
/**
 * Source URL of the iframe
 */
export type Src = string;
/**
 * Width of the iframe
 */
export type Width = number | string;
/**
 * Height of the iframe
 */
export type Height = number | string;
/**
 * Frame border of the iframe
 */
export type Frameborder = number;
/**
 * Scrolling of the iframe
 */
export type Scrolling = string;
/**
 * Allow transparency of the iframe
 */
export type Allowtransparency = boolean;
/**
 * Trigger event for when to execute a run
 */
export type Triggerevent = string;

/**
 * This is a representation of a standard iframe component
 */
export interface IFrame {
  id: Id;
  variable_name?: VariableName;
  component?: Component;
  src?: Src;
  width?: Width;
  height?: Height;
  frameborder?: Frameborder;
  scrolling?: Scrolling;
  allowtransparency?: Allowtransparency;
  triggerEvent?: Triggerevent;
  [k: string]: unknown;
}
