/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Unique id for a component
 */
export type Id = string;
/**
 * Optional variable name associated with a component
 */
export type VariableName = string;
/**
 * Vue component name
 */
export type Component = string;
/**
 * Source URL or Path of the image
 */
export type Src = string;
/**
 * Alternative text for the image
 */
export type Alt = string;
/**
 * Width of the image
 */
export type Width = number;
/**
 * Height of the image
 */
export type Height = number;

/**
 * Image component for displaying web hosted or local images. Supports .png, .jpg, and .jpeg file types
 */
export interface Image {
  id: Id;
  variable_name?: VariableName;
  component?: Component;
  src: Src;
  alt?: Alt;
  width?: Width;
  height?: Height;
  [k: string]: unknown;
}
