/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Unique id for a component
 */
export type Id = string;
/**
 * Optional variable name associated with a component
 */
export type VariableName = string;
export type Row = number | null;
export type Column = number | null;
export type Colwidth = number | null;
/**
 * Vue component name.
 */
export type Component = string;
/**
 * Source URL of the image.
 */
export type Src = string;
/**
 * Alternative text for the image.
 */
export type Alt = string;
/**
 * Width of the image.
 */
export type Width = number;
/**
 * Height of the image.
 */
export type Height = number;

/**
 * A class for Image components inheriting from ZTComponent.
 */
export interface Image {
  id: Id;
  variable_name?: VariableName;
  row?: Row;
  column?: Column;
  colWidth?: Colwidth;
  component?: Component;
  src: Src;
  alt?: Alt;
  width?: Width;
  height?: Height;
  [k: string]: unknown;
}
