/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * List of component IDs that belong to this column
 */
export type Components1 = (string | Row)[];
export type Width = number | boolean;
/**
 * List of columns that belong to this row
 */
export type Components = (string | Column)[];
/**
 * List of rows in this layout
 */
export type Rows = Row[];
/**
 * List of columns in this layout
 */
export type Columns = Column[];

export interface Layout {
  rows?: Rows;
  columns?: Columns;
  [k: string]: unknown;
}
export interface Row {
  components?: Components;
  [k: string]: unknown;
}
export interface Column {
  components?: Components1;
  width?: Width;
  [k: string]: unknown;
}
