/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * List of component IDs and rows that belong to this column, rendered in order
 */
export type Components1 = (string | Row)[];
/**
 * Width of the column. It can be a number 1-12 and by default is automatically calculated
 */
export type Width = number | boolean;
/**
 * List of component IDs and columns that belong to this row, rendered in order
 */
export type Components = (string | Column)[];
/**
 * List of rows in this layout
 */
export type Rows = Row[];

/**
 * Layout is an object that contains the list of rows to be rendered
 */
export interface Layout {
  rows?: Rows;
  [k: string]: unknown;
}
/**
 * Rows can contain both individual components and columns. They are the top level components of a layout and can be subcomponents of columns
 */
export interface Row {
  components?: Components;
  [k: string]: unknown;
}
/**
 * A Column must be a subcomponent of a Row. It can contain both individual components and rows
 */
export interface Column {
  components?: Components1;
  width?: Width;
  [k: string]: unknown;
}
