/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Unique id for a row
 */
export type Id = string;
/**
 * Unique id for a column
 */
export type Id1 = string;
/**
 * List of component IDs that belong to this column
 */
export type Components = (string | ZTRow)[];
/**
 * List of columns that belong to this row
 */
export type Columns = ZTColumn[];
/**
 * List of rows that make up this layout
 */
export type Rows = ZTRow[];

export interface ZTLayout {
  rows?: Rows;
  [k: string]: unknown;
}
export interface ZTRow {
  id: Id;
  columns?: Columns;
  [k: string]: unknown;
}
export interface ZTColumn {
  id: Id1;
  components?: Components;
  [k: string]: unknown;
}
