/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = string;
export type Code = string;
export type Output = string;
export type VariableName = string;
/**
 * List of component IDs that belong to this column
 */
export type Components = (string | ZTRow)[];
/**
 * List of columns that belong to this row
 */
export type Columns = ZTColumn[];
/**
 * List of rows that make up this layout
 */
export type Rows = ZTRow[];
/**
 * Unique id for a component
 */
export type Id1 = string;
/**
 * Optional variable name associated with a component
 */
export type VariableName1 = string;
export type Components1 = ZTComponent[];
export type Celltype = "code" | "markdown" | "text" | "sql";
/**
 * User session ID
 */
export type Userid = string;

export interface Notebook {
  cells: Cells;
  userId?: Userid;
  [k: string]: unknown;
}
export interface Cells {
  [k: string]: CodeCell;
}
export interface CodeCell {
  id: Id;
  code: Code;
  output: Output;
  variable_name: VariableName;
  layout?: ZTLayout;
  components: Components1;
  cellType: Celltype;
  [k: string]: unknown;
}
export interface ZTLayout {
  rows?: Rows;
  [k: string]: unknown;
}
export interface ZTRow {
  columns?: Columns;
  [k: string]: unknown;
}
export interface ZTColumn {
  components?: Components;
  [k: string]: unknown;
}
export interface ZTComponent {
  id: Id1;
  variable_name?: VariableName1;
  [k: string]: unknown;
}
