/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Unique id for a component
 */
export type Id = string;
/**
 * Optional variable name associated with a component
 */
export type VariableName = string;
/**
 * Vue component name
 */
export type Component = string;
/**
 * The input number value
 */
export type Value = number | null;
/**
 * Placeholder number
 */
export type Placeholder = number | null;
/**
 * Label for the number input
 */
export type Label = string | null;
/**
 * If true, the input is read-only
 */
export type Readonly = boolean | null;
/**
 * If true, the input is disabled
 */
export type Disabled = boolean | null;
/**
 * Ensures that only numbers are accepted on the frontend
 */
export type Type = string;
/**
 * Trigger event to send code to the backend
 */
export type Triggerevent = string;

/**
 * Number input allows a user to input an arbitrary number. Can be a float or an integer
 */
export interface NumberInput {
  id: Id;
  variable_name?: VariableName;
  component?: Component;
  value?: Value;
  placeholder?: Placeholder;
  label?: Label;
  readonly?: Readonly;
  disabled?: Disabled;
  type?: Type;
  triggerEvent?: Triggerevent;
  [k: string]: unknown;
}
