/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Unique id for a component
 */
export type Id = string;
/**
 * Optional variable name associated with a component
 */
export type VariableName = string;
/**
 * Vue component name
 */
export type Component = string;
/**
 * The input text value
 */
export type Value = string | number;
/**
 * Vue component name
 */
export type Autofocus = boolean;
/**
 * If true, the input is disabled
 */
export type Disabled = boolean;
/**
 * Color of the switch. Can be custom or standard Material color
 */
export type Color = string;
/**
 * Divider for otp
 */
export type Divider = boolean;
/**
 * Width of the switch
 */
export type Width = number | string;
/**
 * Type of otp
 */
export type Type = string;
/**
 * Trigger event for when to trigger a run
 */
export type Triggerevent = string;
/**
 * Loading for otp
 */
export type Loading = boolean;

/**
 * A Otp component that allows for passwords or authentication
 */
export interface Otp {
  id: Id;
  variable_name?: VariableName;
  component?: Component;
  value?: Value;
  autofocus?: Autofocus;
  disabled?: Disabled;
  color?: Color;
  divider?: Divider;
  width?: Width;
  type?: Type;
  triggerEvent?: Triggerevent;
  loading?: Loading;
  [k: string]: unknown;
}
