/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = string;
/**
 * Unique id for a component
 */
export type Id1 = string;
/**
 * Optional variable name associated with a component
 */
export type VariableName = string;
export type Components = ZTComponent[];
/**
 * List of component IDs that belong to this column
 */
export type Components1 = (string | ZTRow)[];
/**
 * List of columns that belong to this row
 */
export type Columns = ZTColumn[];
/**
 * List of rows that make up this layout
 */
export type Rows = ZTRow[];
export type Output = string;
export type Cells = CellResponse[];

export interface Response {
  cells: Cells;
  [k: string]: unknown;
}
export interface CellResponse {
  id: Id;
  components: Components;
  layout: ZTLayout | null;
  output: Output;
  [k: string]: unknown;
}
export interface ZTComponent {
  id: Id1;
  variable_name?: VariableName;
  [k: string]: unknown;
}
export interface ZTLayout {
  rows?: Rows;
  [k: string]: unknown;
}
export interface ZTRow {
  columns?: Columns;
  [k: string]: unknown;
}
export interface ZTColumn {
  components?: Components1;
  [k: string]: unknown;
}
