/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Unique id for a component
 */
export type Id = string;
/**
 * Optional variable name associated with a component
 */
export type VariableName = string;
export type Components = ZTComponent[];
export type Output = string;
export type Cells = CellResponse[];

export interface Response {
  cells: Cells;
  [k: string]: unknown;
}
export interface CellResponse {
  components: Components;
  output: Output;
  [k: string]: unknown;
}
export interface ZTComponent {
  id: Id;
  variable_name?: VariableName;
  [k: string]: unknown;
}
