/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = string;
/**
 * Unique id for a component
 */
export type Id1 = string;
/**
 * Optional variable name associated with a component
 */
export type VariableName = string;
export type Row = number | null;
export type Column = number | null;
export type Colwidth = number | null;
export type Components = ZTComponent[];
export type Output = string;
export type Cells = CellResponse[];

export interface Response {
  cells: Cells;
  [k: string]: unknown;
}
export interface CellResponse {
  id: Id;
  components: Components;
  output: Output;
  [k: string]: unknown;
}
export interface ZTComponent {
  id: Id1;
  variable_name?: VariableName;
  row?: Row;
  column?: Column;
  colWidth?: Colwidth;
  [k: string]: unknown;
}
