/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = string;
export type Text = string;
export type Line = string;
export type Column = string;

export interface SaveRequest {
  id: Id;
  text: Text;
  line?: Line;
  column?: Column;
  [k: string]: unknown;
}
