/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Unique id for a component
 */
export type Id = string;
/**
 * Optional variable name associated with a component
 */
export type VariableName = string;
export type Row = number | null;
export type Column = number | null;
export type Colwidth = number | null;
/**
 * Vue component name.
 */
export type Component = string;
/**
 * Options for the select box. Can be a list of strings or integers.
 */
export type Value = (string | number)[];
/**
 * Label for the select box.
 */
export type Label = string;
/**
 * Determines if multiple selections are allowed.
 */
export type Multiple = boolean;
/**
 * Determines if the select box is dense.
 */
export type Dense = boolean;
/**
 * Determines if the select box has an outlined style.
 */
export type Outlined = boolean;
/**
 * Determines if the select box has a clearable option.
 */
export type Clearable = boolean;
/**
 * Determines if the select box is disabled.
 */
export type Disabled = boolean;
/**
 * Determines if the select box is read-only.
 */
export type Readonly = boolean;
/**
 * Color of the range slider. Can be custom or standard Material color.
 */
export type Color = string;
/**
 * Trigger event for when to run the slider
 */
export type Triggerevent = string;

/**
 * A class for SelectBox components inheriting from ZTComponent.
 */
export interface SelectBox {
  id: Id;
  variable_name?: VariableName;
  row?: Row;
  column?: Column;
  colWidth?: Colwidth;
  component?: Component;
  value: Value;
  label?: Label;
  multiple?: Multiple;
  dense?: Dense;
  outlined?: Outlined;
  clearable?: Clearable;
  disabled?: Disabled;
  readonly?: Readonly;
  color?: Color;
  triggerEvent?: Triggerevent;
  [k: string]: unknown;
}
