/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Username = string;
export type Projectname = string;
export type Apikey = string;

export interface ShareRequest {
  userName: Username;
  projectName: Projectname;
  apiKey: Apikey;
  [k: string]: unknown;
}
