/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Unique id for a component
 */
export type Id = string;
/**
 * Optional variable name associated with a component
 */
export type VariableName = string;
/**
 * Vue component name
 */
export type Component = string;
/**
 * The input text value
 */
export type Value = string;
/**
 * Hint text for switch
 */
export type Hint = string | null;
/**
 * If true, the input is disabled
 */
export type Disabled = boolean | null;
/**
 * Color of the switch. Can be custom or standard Material color
 */
export type Color = string;
/**
 * A label for your switch
 */
export type Label = string | null;
/**
 * Determines if multiple selections are allowed
 */
export type Multiple = boolean | null;
/**
 * Width of the switch
 */
export type Width = number | string;
/**
 * Trigger event for when to trigger a run
 */
export type Triggerevent = string;
/**
 * Determines if the Switch is read-only
 */
export type Readonly = boolean | null;

/**
 * A slider component that allows a user to select a range of values
 */
export interface Switch {
  id: Id;
  variable_name?: VariableName;
  component?: Component;
  value?: Value;
  hint?: Hint;
  disabled?: Disabled;
  color?: Color;
  label?: Label;
  multiple?: Multiple;
  width?: Width;
  triggerEvent?: Triggerevent;
  readonly?: Readonly;
  [k: string]: unknown;
}
