/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Unique id for a component
 */
export type Id = string;
/**
 * Optional variable name associated with a component
 */
export type VariableName = string;
export type Row = number | null;
export type Column = number | null;
export type Colwidth = number | null;
/**
 * Vue component name.
 */
export type Component = string;
/**
 * The input text value
 */
export type Value = string;
/**
 * Placeholder text.
 */
export type Placeholder = string;
/**
 * Label for the text input.
 */
export type Label = string;
/**
 * If true, the input is read-only.
 */
export type Readonly = boolean;
/**
 * If true, the input is disabled.
 */
export type Disabled = boolean;
/**
 * Trigger event to send code to the backend
 */
export type Triggerevent = string;

/**
 * A class for TextInput components inheriting from ZTComponent.
 */
export interface TextInput {
  id: Id;
  variable_name?: VariableName;
  row?: Row;
  column?: Column;
  colWidth?: Colwidth;
  component?: Component;
  value?: Value;
  placeholder?: Placeholder;
  label?: Label;
  readonly?: Readonly;
  disabled?: Disabled;
  triggerEvent?: Triggerevent;
  [k: string]: unknown;
}
