/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Unique id for a component
 */
export type Id = string;
/**
 * Optional variable name associated with a component
 */
export type VariableName = string;
/**
 * Vue component name
 */
export type Component = string;
/**
 * Interval in milliseconds
 */
export type Interval = number;
/**
 * Flag for execution under interval
 */
export type Value = boolean;
/**
 * Trigger event for when to execute a run
 */
export type Triggerevent = string;

/**
 * Timer is a component that allows for execution of code at a set interval. This does not have any visual output
 */
export interface Timer {
  id: Id;
  variable_name?: VariableName;
  component?: Component;
  interval?: Interval;
  value?: Value;
  triggerEvent?: Triggerevent;
  [k: string]: unknown;
}
