name: Update Mintlify Documentation

on:
  push:
    branches:
      - main

jobs:
  update-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Trigger Mintlify Update
      run: |
        curl --request POST         --url https://api.mintlify.com/v1/project/update/${{ secrets.MINTLIFY_PROJECT_ID }}         --header 'Authorization: Bearer ${{ secrets.MINTLIFY_API_KEY }}'
